version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data:
